- hosts: all
  gather_facts: no

  tasks:
    - name: Special task
      command: echo 'yeah!'
      register: result
      tags: special

    - name: 'Check tags'
      fail:
        msg: 'Expected result is defined'
      when: result is not defined
      tags: special

