- hosts: selectel
  vars:
    string: "This is server {{ ansible_hostname }}" 
    date: "{{ ansible_date_time.iso8601 }}"
    root_dir: /usr/share/nginx/html/
  tasks:
    - name: cp index.html
      ansible.builtin.template: 
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      notify: 
        - restart nginx
      become: yes
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes