---

-
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: files/hosts
        dest: /tmp/hosts

    - name: Set file mode for `/tmp/hosts` to 777
      ansible.builtin.file:
        path: /tmp/hosts
        mode: '777'

    - name: Retrieve file status
      ansible.builtin.stat:
        path: /tmp/hosts
        get_checksum: false
        get_attributes: false
        get_mime: false
      register: result

    - name: Check file mode for `/tmp/hosts`
      ansible.builtin.fail:
        msg: "Expected `777` mode, but was `{{ result.stat.mode }}`"
      when: result.stat.mode != "0777"
