- hosts: all
  roles:
    - name: hexlet.timezone

  tasks:
    - name: Set vars
      import_role:
        name: hexlet.timezone
      vars:
        timezone: America/New_York

    - name: Get current timezone
      set_fact:
        current_timezone: "{{ lookup('file', '/etc/timezone') }}"

    - name: Check result
      fail:
        msg: "Expected `America/New_York` but was `{{ current_timezone }}`"
      when: current_timezone is not defined or current_timezone != 'America/New_York'
