- hosts: selectel
  tasks:
    - name: add users
      ansible.builtin.user:
        name: "{{ item }}"
      become: yes
      loop:
      - sansa
      - jamie
      - robert

    - name: copy file 
      ansible.builtin.template:
        src: files/.gitconfig
        dest: /home/"{{ item }}"/.gitconfig
      become: yes
      loop:
      - sansa
      - jamie
      - robert
  